[toolchain]
package_manager = "yarn"

[features]
idl-build = ["anchor-spl/idl-build"]
resolution = true
skip-lint = false

[programs.localnet]
roulette = "JAVuBXeBZqXNtS73azhBDAoYaaAFfo4gWXoZe2e7Jf8H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
